export const VisaData = [
  {
    img: 'https://media.atlys.com/image/upload/f_auto,w_800/country_thumbnails/AE',
    appliedVisas: '53K+',
    place: 'United Arab Emirates',
    price: '2,500',
    getOn: '12 Jun, 12:12 PM',
  },
  {
    img: 'https://media.atlys.com/image/upload/f_auto,w_800/country_thumbnails/EG',
    appliedVisas: '55K+',
    place: 'Egypt',
    price: '2,500',
    getOn: '12 Jun, 12:12 PM',
  },
  {
    img: 'https://media.atlys.com/image/upload/f_auto,w_800/country_thumbnails/SG',
    appliedVisas: '60K+',
    place: 'Singapore',
    price: '2,500',
    getOn: '12 Jun, 12:12 PM',
  },
  {
    img: 'https://media.atlys.com/b2c/country_thumbnails/tr:w-800/JP',
    appliedVisas: '45K+',
    place: 'Japan',
    price: '2,500',
    getOn: '12 Jun, 12:12 PM',
  },
  {
    img: 'https://media.atlys.com/image/upload/f_auto,w_800/country_thumbnails/TR',
    appliedVisas: '58K+',
    place: 'Türkiye',
    price: '2,500',
    getOn: '12 Jun, 12:12 PM',
  },
  {
    img: 'https://media.atlys.com/image/upload/f_auto,w_800/country_thumbnails/MY',
    appliedVisas: '50K+',
    place: 'Malaysia',
    price: '2,500',
    getOn: '12 Jun, 12:12 PM',
  },
  {
    img: 'https://media.atlys.com/image/upload/f_auto,w_800/country_thumbnails/VN',
    appliedVisas: '48K+',
    place: 'Vietnam',
    price: '2,500',
    getOn: '12 Jun, 12:12 PM',
  },
  {
    img: 'https://media.atlys.com/image/upload/f_auto,w_800/country_thumbnails/OM',
    appliedVisas: '35K+',
    place: 'Oman',
    price: '2,500',
    getOn: '12 Jun, 12:12 PM',
  },
  {
    img: 'https://media.atlys.com/b2c/country_thumbnails/tr:w-800/TH',
    appliedVisas: '70K+',
    place: 'Thailand',
    price: '2,500',
    getOn: '12 Jun, 12:12 PM',
  },
  {
    img: 'https://media.atlys.com/image/upload/f_auto,w_800/country_thumbnails/LK',
    appliedVisas: '20K+',
    place: 'Sri Lanka',
    price: '2,500',
    getOn: '12 Jun, 12:12 PM',
  },
  {
    img: 'https://media.atlys.com/image/upload/f_auto,w_800/country_thumbnails/GE',
    appliedVisas: '15K+',
    place: 'Georgia',
    price: '2,500',
    getOn: '12 Jun, 12:12 PM',
  },
];
